version: '3.8'

services:
  database:
    container_name: mysql_db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: high-dev
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: 'high-dev-admin'
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # networks:
    #   - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
    driver: local

# networks:
#   backend:
#     driver: bridge
    # volumes:
    #   - ./mysql/conf.d:/etc/mysql # MySQL 설정 파일 위치
    # command:
    #   - "mysqld"
    #   - "--character-set-server=utf8mb4"
    #   - "--collation-server=utf8mb4_unicode_ci"
    

  # application:
  #   container_name: docker-compose-test
  #   restart: on-failure
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/users_db?useSSL=false&allowPublicKeyRetrieval=true
  #     SPRING_DATASOURCE_USERNAME: "root"
  #     SPRING_DATASOURCE_PASSWORD: "1234"
  #   depends_on:
  #     - database
  #   networks:
  #     - test_network

# networks:
#   test_network:

#   image: mysql:8.0.23
#     container_name: prd-db
#     platform: linux/amd64
#     ports:
#       - 3306:3306
#     environment: 
#       MYSQL_RANDOM_ROOT_PASSWORD: yes
#       MYSQL_USER: classum-dev
#       MYSQL_PASSWORD: 9082
#       MYSQL_DATABASE: classum
#     healthcheck:
#       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#       timeout: 20s
#       retries: 10

  